CREATE TABLE IF NOT EXISTS body_parts 
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) UNIQUE NOT NULL COMMENT '部位名',
    body_part_group_id BIGINT UNSIGNED NOT NULL COMMENT '部位グループID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (body_part_group_id)
        REFERENCES body_part_groups(id)
        ON DELETE CASCADE
) COMMENT '部位マスタ';