CREATE TABLE IF NOT EXISTS body_part_groups
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(10) NOT NULL COMMENT '部位グループ名',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) COMMENT '部位グループマスタ';